import { useState } from 'react'
import { useKV } from '@github/spark/hooks'
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Card } from '@/components/ui/card'
import { Toaster } from '@/components/ui/sonner'
import { Agent, NFT, TerminalLog, Event } from '@/lib/types'
import { getMockAgents, getMockNFTs, getMockEvents } from '@/lib/mockData'
import { AgentCard } from '@/components/AgentCard'
import { NFTCard } from '@/components/NFTCard'
import { SpawnAgentDialog } from '@/components/SpawnAgentDialog'
import { TerminalConsole } from '@/components/TerminalConsole'
import { Sparkle, Robot, Wallet, ChartLine, Globe, Plus } from '@phosphor-icons/react'
import { toast } from 'sonner'
import { motion } from 'framer-motion'

function App() {
  const [agents, setAgents] = useKV<Agent[]>('maef-agents', getMockAgents())
  const [nfts, setNFTs] = useKV<NFT[]>('maef-nfts', getMockNFTs())
  const [events, setEvents] = useKV<Event[]>('maef-events', getMockEvents())
  const [logs, setLogs] = useState<TerminalLog[]>([])
  
  const [spawnDialogOpen, setSpawnDialogOpen] = useState(false)
  const [selectedTab, setSelectedTab] = useState('dashboard')
  const [eventUrl, setEventUrl] = useState('')

  const handleAgentCreated = (newAgent: Agent) => {
    setAgents((current) => [...(current ?? []), newAgent])
    toast.success(`Agent "${newAgent.name}" spawned successfully!`, {
      description: `Wallet: ${newAgent.walletAddress.slice(0, 10)}...`
    })
    
    addLog(newAgent.id, 'secretary', 'Agent initialization complete', 'success')
  }

  const addLog = (agentId: string, subAgentType: Agent['subAgents'][0]['type'], message: string, type: TerminalLog['type']) => {
    const log: TerminalLog = {
      id: `log-${Date.now()}-${Math.random()}`,
      agentId,
      subAgentType,
      message,
      timestamp: Date.now(),
      type
    }
    setLogs((current) => [...current, log])
  }

  const handleAttendEvent = async () => {
    if (!eventUrl.trim()) {
      toast.error('Please enter an event URL')
      return
    }

    if (!agents || agents.length === 0) {
      toast.error('No agents available. Spawn an agent first!')
      return
    }
    const agent = agents[0]

    toast.info('Initiating event attendance workflow...')
    
    addLog(agent.id, 'secretary', `Joining event: ${eventUrl}`, 'info')
    await new Promise(resolve => setTimeout(resolve, 1000))
    
    addLog(agent.id, 'secretary', 'Registration successful', 'success')
    await new Promise(resolve => setTimeout(resolve, 800))
    
    addLog(agent.id, 'scribe', 'Extracting event content...', 'info')
    await new Promise(resolve => setTimeout(resolve, 1500))
    
    addLog(agent.id, 'scribe', 'Generating summary with AI...', 'info')
    await new Promise(resolve => setTimeout(resolve, 1200))
    
    addLog(agent.id, 'scribe', 'Summary generated successfully', 'success')
    await new Promise(resolve => setTimeout(resolve, 500))
    
    addLog(agent.id, 'mint-master', 'Estimating Mantle gas fees...', 'info')
    await new Promise(resolve => setTimeout(resolve, 800))
    
    addLog(agent.id, 'mint-master', 'Minting NFT on Mantle Network...', 'info')
    await new Promise(resolve => setTimeout(resolve, 1500))
    
    addLog(agent.id, 'mint-master', 'NFT minted successfully! 🎉', 'success')

    const newEvent: Event = {
      id: `event-${Date.now()}`,
      agentId: agent.id,
      url: eventUrl,
      title: 'New Event Attended',
      platform: 'YouTube',
      date: Date.now(),
      summary: 'Event summary generated by AI agent.',
      status: 'completed'
    }

    const newNFT: NFT = {
      id: `nft-${Date.now()}`,
      agentId: agent.id,
      eventId: newEvent.id,
      eventTitle: newEvent.title,
      summary: newEvent.summary,
      date: Date.now(),
      transactionHash: `0x${Math.random().toString(16).slice(2)}`,
      tokenId: `${1000 + (nfts?.length ?? 0) + 1}`,
      imageUrl: 'https://placehold.co/400x400/1a1b3a/00f3ff?text=MAEF+NFT'
    }

    setEvents((current) => [...(current ?? []), newEvent])
    setNFTs((current) => [...(current ?? []), newNFT])
    setAgents((current) =>
      (current ?? []).map((a) =>
        a.id === agent.id
          ? { ...a, eventsAttended: a.eventsAttended + 1, level: Math.floor((a.eventsAttended + 1) / 2) + 1, wisdomUnlocked: a.eventsAttended + 1 >= 5 }
          : a
      )
    )

    setEventUrl('')
    toast.success('Event attendance complete! NFT minted.', {
      description: `Transaction: ${newNFT.transactionHash.slice(0, 10)}...`
    })
  }

  const stats = [
    { label: 'Active Agents', value: agents?.length ?? 0, icon: Robot, color: 'text-primary' },
    { label: 'NFTs Minted', value: nfts?.length ?? 0, icon: Wallet, color: 'text-secondary' },
    { label: 'Events Attended', value: events?.length ?? 0, icon: Globe, color: 'text-primary' },
    { label: 'Wisdom Unlocked', value: agents?.filter(a => a.wisdomUnlocked).length ?? 0, icon: ChartLine, color: 'text-secondary' }
  ]

  return (
    <div className="min-h-screen bg-background relative overflow-hidden">
      <div className="absolute inset-0 bg-[radial-gradient(circle_at_30%_20%,rgba(0,243,255,0.1),transparent_50%),radial-gradient(circle_at_80%_80%,rgba(157,0,255,0.1),transparent_50%)]" />
      <div className="absolute inset-0 bg-[url('data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjAwIiBoZWlnaHQ9IjIwMCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48ZGVmcz48cGF0dGVybiBpZD0iZ3JpZCIgd2lkdGg9IjQwIiBoZWlnaHQ9IjQwIiBwYXR0ZXJuVW5pdHM9InVzZXJTcGFjZU9uVXNlIj48cGF0aCBkPSJNIDQwIDAgTCAwIDAgMCA0MCIgZmlsbD0ibm9uZSIgc3Ryb2tlPSJyZ2JhKDI1NSwyNTUsMjU1LDAuMDMpIiBzdHJva2Utd2lkdGg9IjEiLz48L3BhdHRlcm4+PC9kZWZzPjxyZWN0IHdpZHRoPSIxMDAlIiBoZWlnaHQ9IjEwMCUiIGZpbGw9InVybCgjZ3JpZCkiLz48L3N2Zz4=')] opacity-40" />

      <div className="relative z-10">
        <header className="border-b border-border/50 backdrop-blur-sm bg-background/80 sticky top-0 z-40">
          <div className="container mx-auto px-6 py-4">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-3">
                <div className="w-10 h-10 rounded-lg bg-gradient-to-br from-primary to-secondary flex items-center justify-center animate-glow-pulse">
                  <Sparkle size={24} className="text-background" weight="fill" />
                </div>
                <div>
                  <h1 className="text-2xl font-bold tracking-tight">MAEF</h1>
                  <p className="text-xs text-muted-foreground">Mantle Agentic Event Factory</p>
                </div>
              </div>
              <p className="text-sm text-muted-foreground italic hidden md:block">
                Turn Information Overload into On-Chain Wisdom
              </p>
            </div>
          </div>
        </header>

        <main className="container mx-auto px-6 py-8 pb-64">
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4 mb-8">
            {stats.map((stat, i) => (
              <motion.div
                key={stat.label}
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: i * 0.1 }}
              >
                <Card className="glass-card p-4">
                  <div className="flex items-center justify-between">
                    <div>
                      <p className="text-xs text-muted-foreground uppercase tracking-wider">{stat.label}</p>
                      <p className="text-2xl font-bold mt-1">{stat.value}</p>
                    </div>
                    <stat.icon size={32} className={stat.color} weight="duotone" />
                  </div>
                </Card>
              </motion.div>
            ))}
          </div>

          <Tabs value={selectedTab} onValueChange={setSelectedTab} className="w-full">
            <TabsList className="glass-card mb-6">
              <TabsTrigger value="dashboard">Dashboard</TabsTrigger>
              <TabsTrigger value="factory">Factory</TabsTrigger>
              <TabsTrigger value="vault">NFT Vault</TabsTrigger>
            </TabsList>

            <TabsContent value="dashboard" className="space-y-6">
              <Card className="glass-card p-6">
                <h2 className="text-xl font-bold mb-4 flex items-center gap-2">
                  <Globe className="text-primary" weight="duotone" />
                  Attend Event
                </h2>
                <div className="flex gap-3">
                  <Input
                    placeholder="Enter YouTube or Luma event URL..."
                    value={eventUrl}
                    onChange={(e) => setEventUrl(e.target.value)}
                    className="flex-1 border-primary/20 focus:border-primary"
                  />
                  <Button
                    onClick={handleAttendEvent}
                    disabled={!eventUrl.trim()}
                    className="bg-gradient-to-r from-secondary to-accent hover:opacity-90"
                  >
                    Attend Event
                  </Button>
                </div>
              </Card>

              <div>
                <h2 className="text-xl font-bold mb-4">Your Agents</h2>
                {!agents || agents.length === 0 ? (
                  <Card className="glass-card p-12 text-center">
                    <Robot size={64} className="mx-auto mb-4 text-muted-foreground" weight="duotone" />
                    <h3 className="text-lg font-semibold mb-2">No Agents Yet</h3>
                    <p className="text-sm text-muted-foreground mb-4">Spawn your first AI agent to get started</p>
                    <Button onClick={() => setSpawnDialogOpen(true)} className="bg-gradient-to-r from-secondary to-accent">
                      <Plus className="mr-2" weight="bold" />
                      Spawn Agent
                    </Button>
                  </Card>
                ) : (
                  <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                    {agents.map((agent) => (
                      <AgentCard key={agent.id} agent={agent} />
                    ))}
                  </div>
                )}
              </div>
            </TabsContent>

            <TabsContent value="factory" className="space-y-6">
              <Card className="glass-card p-8 text-center">
                <Sparkle size={64} className="mx-auto mb-4 text-primary" weight="fill" />
                <h2 className="text-2xl font-bold mb-2">Agent Factory</h2>
                <p className="text-muted-foreground mb-6">
                  Create autonomous AI agents tailored to your information needs
                </p>
                <Button
                  onClick={() => setSpawnDialogOpen(true)}
                  size="lg"
                  className="bg-gradient-to-r from-secondary to-accent hover:opacity-90"
                >
                  <Plus className="mr-2" weight="bold" />
                  Spawn New Agent
                </Button>
              </Card>

              <div>
                <h3 className="text-xl font-bold mb-4">All Agents ({agents?.length ?? 0})</h3>
                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                  {agents?.map((agent) => (
                    <AgentCard key={agent.id} agent={agent} />
                  ))}
                </div>
              </div>
            </TabsContent>

            <TabsContent value="vault" className="space-y-6">
              <div className="flex items-center justify-between mb-4">
                <h2 className="text-xl font-bold">NFT Vault</h2>
                <p className="text-sm text-muted-foreground">{nfts?.length ?? 0} NFTs minted</p>
              </div>
              
              {!nfts || nfts.length === 0 ? (
                <Card className="glass-card p-12 text-center">
                  <Wallet size={64} className="mx-auto mb-4 text-muted-foreground" weight="duotone" />
                  <h3 className="text-lg font-semibold mb-2">No NFTs Yet</h3>
                  <p className="text-sm text-muted-foreground">
                    Attend events with your agents to mint Proof-of-Attendance NFTs
                  </p>
                </Card>
              ) : (
                <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-6">
                  {nfts?.map((nft) => (
                    <NFTCard key={nft.id} nft={nft} />
                  ))}
                </div>
              )}
            </TabsContent>
          </Tabs>
        </main>
      </div>

      <SpawnAgentDialog
        open={spawnDialogOpen}
        onOpenChange={setSpawnDialogOpen}
        onAgentCreated={handleAgentCreated}
      />

      <TerminalConsole logs={logs} />
      <Toaster />
    </div>
  )
}

export default App